org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.1+26.x
maven_group=io.github.mintynoura.shattermyeyes
archives_base_name=shattermyeyes

# Dependencies
fabric_version=0.153.0+26.2