org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.1+26.1.x
maven_group=io.github.mintynoura.shattermyeyes
archives_base_name=shattermyeyes

# Dependencies
fabric_version=0.144.4+26.1